---
groups:
  - name: puppet-enterprise-nodes
    config:
      transport: ssh
      ssh:
        tmpdir: /root
        script-dir: test123
        host-key-check: false
        user: root
        password: test
        tty: true
    targets:
      - pe-std.puppet.vm
