---
groups:
  - name: puppet-enterprise-nodes
    config:
      transport: ssh
      ssh:
        tmpdir: /root/bolt_scripts
        host-key-check: false
        user: root
        password: test
        tty: true
    targets:
      - pe-std.puppet.vm
      - pe-std-replica.puppet.vm
